name: my_pat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.21.0
  fluro: ^1.4.0
  dio: ^2.1.0
  logging: 0.11.3+2
  path_provider: ^0.5.0+1
  connectivity: ^0.4.2
  flutter_blue: 0.5.0
  date_format: ^1.0.6
  shared_preferences: ^0.5.1+1
  stack_trace: ^1.9.3
  get_it: ^1.0.3
  sprintf: ^4.0.2
  flutter_local_notifications: ^0.7.0


#  battery: ^0.3.0+1
#  ssh: ^0.0.3

  battery:
    path: ../../../../derzhavets/projects/flutter_plugins/packages/battery/

  ssh:
    path: ../../../../derzhavets/projects/flutter_ssh/


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/carousel/
    - assets/indicator/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
